routes/web.php
<?php


Route::get('','LoginController@view_login')->name('view_login');
Route::post('process_login','LoginController@process_login')->name('process_login');

Route::group(['middleware' => 'CheckLogin'],function(){
	Route::get('welcome','Controller@welcome')->name('welcome');


	Route::group(['as' => 'sinh_vien.', 'prefix' => 'sinh_vien'],function(){
		Route::get('choose_by_lop','SinhVienController@choose_by_lop')->name('choose_by_lop');
		Route::get('view_by_lop','SinhVienController@view_by_lop')->name('view_by_lop');

		// đổi ảnh
		Route::get('view_change_anh/{ma}','SinhVienController@view_change_anh')->name('view_change_anh');
		Route::post('process_change_anh/{ma}','SinhVienController@process_change_anh')->name('process_change_anh');

		// làm việc với file excel
		Route::get('view_insert_with_excel','SinhVienController@view_insert_with_excel')->name('view_insert_with_excel');
		Route::post('process_insert_with_excel','SinhVienController@process_insert_with_excel')->name('process_insert_with_excel');

		Route::get('export_excel_from_view_all','SinhVienController@export_excel_from_view_all')->name('export_excel_from_view_all');
	});
	Route::resource('sinh_vien','SinhVienController');




	Route::resource('lop','LopController');

	Route::get('logout','LoginController@logout')->name('logout');
});

Route::get('send_mail','Controller@send_mail');

app/Models/Lop.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Lop extends Model
{
    protected $table = 'lop';
    protected $fillable = ['ten'];
    protected $primaryKey = 'ma';

    public $timestamps = false;
    public function sinh_viens()
    {
        return $this->hasMany('App\Models\SinhVien','ma_lop','ma');
    }
}

app/Models/SinhVien.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use DateTime;

class SinhVien extends Model
{
    protected $table = 'sinh_vien';
    protected $fillable = ['ten','ngay_sinh','gioi_tinh','anh','ma_lop'];
    protected $primaryKey = 'ma';

    public $timestamps = false;
    public function lop()
    {
        return $this->belongsTo('App\Models\Lop','ma_lop');
    }

    public function getTuoiAttribute()
    {
		$age = date_diff(date_create($this->ngay_sinh), date_create('now'))->y;
	    return $age;
    }
    public function getTenGioiTinhAttribute()
    {
    	if($this->gioi_tinh==1){
    		return "Nu";
    	}
    	else{
    		return "Nam";
    	}
    }
}

app/Http/Controllers/LopController.php
<?php

namespace App\Http\Controllers;

use App\Models\Lop;
use Illuminate\Http\Request;

class LopController extends Controller
{
    protected $table = 'lop';
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $tim_kiem = $request->get('tim_kiem');
        $array_lop = Lop::where('ten','like',"%$tim_kiem%")->paginate(1);
        return view("$this->table.index",[
            'array_lop' => $array_lop,
            'tim_kiem' => $tim_kiem,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("$this->table.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $lop = new Lop;
        $lop->ten = $request->get('ten');
        $lop->save();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Lop  $Lop
     * @return \Illuminate\Http\Response
     */
    public function show($ma)
    {
        // $lop = Lop::where('ma',$ma)->first();
        $lop = Lop::find($ma);
        return $lop->ten;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Lop  $Lop
     * @return \Illuminate\Http\Response
     */
    public function edit($ma)
    {
        $lop = Lop::find($ma);

        return view("$this->table.edit",[
            'lop' => $lop
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Lop  $Lop
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $ma)
    {
        $lop = Lop::find($ma);
        $lop->ten = $request->get('ten');
        $lop->save();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Lop  $Lop
     * @return \Illuminate\Http\Response
     */
    public function destroy($ma)
    {
        Lop::find($ma)->delete();
    }
}

resources/views/lop/create.blade.php
<form action="{{ route('lop.store') }}" method="post">
	{{csrf_field()}}
	Ten
	<input type="text" name="ten">
	<br>
	<button>Them</button>
</form>

resources/views/lop/edit.blade.php
<form action="{{ route('lop.update',['ma' => $lop->ma]) }}" method="post">
	<input type="hidden" name="_method" value="PUT">
	{{csrf_field()}}
	Ten
	<input type="text" name="ten" value="{{$lop->ten}}">
	<br>
	<button>Sua</button>
</form>

resources/views/lop/index.blade.php
<a href="{{ route('lop.create') }}">
	Thêm
</a>
<table border="1" width="100%">
	<caption>
		<form>
			Tim kiem theo ten
			<input type="search" name="tim_kiem" value="{{$tim_kiem}}">
		</form>
	</caption>
	<tr>
		<th>Tên</th>
		<th>Tuổi</th>
		<th>Xem</th>
		<th>Sửa</th>
		<th>Xóa</th>
	</tr>
	@foreach ($array_lop as $lop)
		<tr>
			<td>
				{{$lop->ten}}
			</td>
			<td>
				{{$lop->tuoi}}
			</td>
			<td>
				<a href="{{ route('lop.show',['ma' => $lop->ma]) }}">
					Xem
				</a>
			</td>
			<td>
				<a href="{{ route('lop.edit',['ma' => $lop->ma]) }}">
					Sua
				</a>
			</td>
			<td>
				<form action="{{ route('lop.destroy',['ma' => $lop->ma]) }}" method="post">
					{{csrf_field()}}
					<input type="hidden" name="_method" value="DELETE">
					<button>Xoa</button>
				</form>
			</td>
		</tr>
	@endforeach
</table>
{{$array_lop->appends(['tim_kiem' => $tim_kiem])->links()}}